---
- name: Setup secrets
  include_vars: secrets.yml
  tags:
    - packer

- name: Bootstrap python for ansible
  raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
  tags:
    - packer

# - name: boostrap locale
#   raw: (locale-gen en_US.UTF-8 && dpkg-reconfigure locales) || (apt-get -y update && apt-get install -y  locales)
