---

- name: meson - test for pre-existing install
  command: meson --version
  register: meson_test
  ignore_errors: True

- name: meson - pip install
  block:
    - name: meson - pip install local --user using pip3
      pip:
        name: "{{ meson_version }}"
        executable: "{{ pip_ex }}"
        extra_args: "--user"
      become: no
      tags:
        - local
      when: docker_run is not defined

    - name: meson - install for root using pip3
      pip:
        name: "{{ meson_version }}"
        executable: "{{ pip_ex }}"
        # extra_args: "--user"
      tags:
          - docker
          - root
      when: docker_run is defined

  when: meson_test is failed
  tags:
    - pip
