if: branch = travis

language: generic

os: linux
dist: bionic

addons:
  apt:
    packages:
      - python-pip

install:
  - sudo pip install ansible

script:
  - cd install
  - travis_wait 30 ansible-playbook ansible/install_local.yml
  - cd ..
  - python unit_tests.py
