---

- name: fson - Set path variable
  set_fact:
    fson_path: "{{ base_dir + '/software/fson'}}"
    fson_build_path: "{{ fson_path + '/build' }}"

- name: fson - Clean path
  file:
    state: absent
    path: "{{ fson_path }}"
  tags:
    - clean

- name: fson - Fetch from github
  git:
    repo: 'https://github.com/josephalevin/fson.git'
    dest: "{{ fson_path }}"
    version: master

- name: fson - change ownership
  file:
    dest: "{{ fson_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  when: docker_run is defined

- name: fson - meson build
  shell: 'meson build --buildtype=release --prefix={{ base_dir }} --libdir={{ lib_path }} --includedir={{ include_path }}'
  args:
    chdir: "{{ fson_path }}"

- name: fson - ninja build
  shell: ninja
  args:
    chdir: "{{ fson_build_path }}"

- name: fson - ninja test
  shell: ninja test
  args:
    chdir: "{{ fson_build_path }}"

- name: fson - ninja install
  shell: ninja install
  args:
    chdir: "{{ fson_build_path }}"
