---

- name: ninja - test for pre-existing install
  command: ninja --version
  register: ninja_test
  ignore_errors: True

- name: ninja - local install
  block:

  - name: ninja - Set path variable
    set_fact:
      ninja_path: "{{ base_dir + '/software/ninja'}}"

  - name: ninja - Clean path
    file:
      state: absent
      path: "{{ ninja_path }}"
    tags:
      - never
      - tidy

  - name: ninja - Fetch from github
    git:
      repo: 'https://github.com/ninja-build/ninja.git'
      dest: "{{ ninja_path }}"
      version: master

  - name: ninja - change ownership
    file:
      dest: "{{ ninja_path }}"
      owner: "{{ app_user }}"
      group: "{{ app_group }}"
      recurse: yes
    when: docker_run is defined


  - name: ninja - run configure script
    command: ./configure.py --bootstrap
    args:
       chdir: "{{ ninja_path }}"
    tags:
      - configure
      - build

  - name: ninja - Copy to bin directory
    copy:
      src: "{{ ninja_path + '/ninja'}}"
      dest: "{{ bin_path }}/ninja"
      remote_src: yes

  - name: ninja - give ninja executable permissions
    file:
      dest: '{{ bin_path }}/ninja'
      mode: a+x

  when: ninja_test is failed
