---

- name: openmpi - Set path variable
  set_fact:
    openmpi_path: "{{ software_path }}/openmpi"

- name: openmpi - tidy paths
  file:
    state: absent
    path: '{{ base_dir }}/openmpi'
  tags:
    - never
    - tidy

- name: openmpi - Dowload and unarchive openmpi
  unarchive:
    src: https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.3.tar.gz
    dest: '{{ software_path }}/openmpi'
    remote_src: yes
  tags:
    - fetch

# - name: openmpi -  Move to non-versioned directory name
#   command: 'mv -n {{software_path}}/openmpi-3.1.3 {{openmpi_path }}'

- name: openmpi - ./configure
  command: >
    ./configure --prefix="{{ base_dir }}" --with-tm
  args:
    chdir: '{{ openmpi_path }}'
  tags:
    - configure
    - build

- name: openmpi - make and install
  block:
  - name: openmpi - make
    make:
      chdir: '{{ openmpi_path }}'

  - name: openmpi - make install
    make:
      chdir: '{{ openmpi_path }}'
        target: install
  tags:
    - make
    - build