---

- name: petsc - Fetch from bitbucket
  git:
    repo: "{{ petsc_repo }}"
    dest: "{{ petsc_path }}"
    version: "{{ petsc_version }}"
  tags:
    - fetch

- name: petsc - change ownership folder ownership
  file:
    dest: "{{ petsc_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  when: docker_run is defined

- name: petsc - configure make
  block:

  - set_fact:
      configure_cmd: "{{ './configure --'  + petsc_options | join(' --') }}"

  - set_fact:
      configure_cmd: "{{ configure_cmd + petsc_variables | join(' ') }}"
    tags:
      - never
      - nesi

  - name: petsc - Run ./configure
    command: "{{ configure_cmd }}"
    args:
      chdir: "{{ petsc_path }}"
  tags:
    - configure
    - build

- name: petsc - make
  block:
  - name: petsc - make all
    make:
      target: all
      chdir: "{{ petsc_path }}"

  - name: petsc - make check
    make:
      target: check
      chdir: "{{ petsc_path }}"

  - name: petsc - make test
    make:
      target: test
      chdir: "{{ petsc_path }}"
  tags:
    - make
    - build

- name: petsc - copy to pkgconfig
  copy:
    src: "{{ petsc_path + '/' + petsc_arch +  '/lib/pkgconfig/PETSc.pc'}}"
    dest: "{{ pkgconfig_path }}/PETSc.pc"
    remote_src: yes
