build_tools:
  - git
  - pkg-config
  - valgrind
  - ninja-build
  - make
  - cmake
  # - python
  # - python-dev
  - python3
  - python3-dev
  - python-setuptools

compilers:
  - gcc
  - g++
  - gfortran

libraries:
  - libopenmpi-dev
  - libblas-dev
  - liblapack-dev

petsc_dependencies:
  - bison
  - flex

pip_install:
  - python3-pip

pip_ex: pip3
