- name: Set docker_status
  set_fact:
    docker_run: True

- name: create user and group
  block:
  - user:
      name: "{{ app_user }}"
      shell: /bin/bash
      uid: 1000
      comment: waiwera app user

  - group:
      name: "{{ app_group }}"
      # shell: /bin/bash
      gid: 1000
      # comment: waiwera app user
  become: yes

- debug:
    msg: "openmpi {{ openmpi }}"

- import_role:
    name: common
  vars:
    base_dir: "{{ d_dir }}"
    app_user: "{{ d_group }}"
    app_group: "{{ d_user }}"
    # openmpi:  "{{ d_openmpi }}"

- name: set entrypoint.sh with template
  template:
    src: entrypoint.j2
    dest: '{{ waiwera_path }}/entrypoint.sh'
    mode: a+x
  become: no

- name: Cleanup
  include: cleanup.yml
  tags:
    - cleanup

- name: change app deployment ownership
  file:
    dest: "{{ waiwera_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  tags:
    - docker
    - root

- name: change /usr/local deployment ownership
  file:
    dest: /usr/local
    owner: root
    group: root
    recurse: yes
  tags:
    - docker
    - root