---

- name: Set path variable
  set_fact:
    ninja_path: "{{ base_dir + '/software/ninja'}}"

- name: Clean path
  file:
    state: absent
    path: "{{ ninja_path }}"
  tags:
    - never
    - tidy

- name: Fetch from github
  git:
    repo: 'https://github.com/ninja-build/ninja.git'
    dest: "{{ ninja_path }}"
    version: master

- name: Change ownership
  file:
    dest: "{{ ninja_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  when: docker_run == true

- name: ninja - run configure script
  command: ./configure.py --bootstrap
  args:
     chdir: "{{ ninja_path }}"
  tags:
    - configure
    - build

- name: Copy to bin directory
  copy:
    src: "{{ ninja_path + '/ninja'}}"
    dest: "{{ bin_path }}/ninja"
    remote_src: yes

- name: Give ninja executable permissions
  file:
    dest: '{{ bin_path }}/ninja'
    mode: a+x
