---

- name: Install multiple base packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - g++-6
    - bison
    - flex
    - cmake
    - git
    - valgrind
    - zlib1g-dev
    - python
    - gem
    - rake
    - gfortran-6
    - unzip
    - libopenmpi-dev
    - liblapack-dev
    - libblas-dev

- name: Symlink gfortran-6 to gfortran
  file:
    src: /usr/bin/gfortran-6
    dest: /usr/bin/gfortran
    state: link

- name: Install python pip
  apt:
    name: python-pip
    state: present

- name: Update pip to lates version with pip
  pip:
    name: pip

- name: Intall pip packages
  pip:
    name:
      - virtualenv
      - h5py
      - virtualenvwrapper
      - numpy
      - shapely
      - future
      - pillow
      - matplotlib
      - scipy
      - meshio

- name: set opt_paths
  copy:
    src: "{{ role_path }}/files/opt_paths.sh"
    dest: /etc/profile.d/opt_paths.sh
    remote_src: yes
  tags:
    - not_packer

- name: Clean app directory structure
  file:
    state: absent
    path: /opt/app/{{ item }}
  with_items:
  - bin
  - lib
  - include

- name: Creates app directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/app
    - /opt/app/bin
    - /opt/app/lib
    - /opt/app/include
