---

- name: Install build-related tools
  package:
    name: "{{ build_tools }}"
    state: present
    update_cache: yes
  # vars:
  #   packages:
  #   - git
  #   - pkg-config
  #   - valgrind
  #   - ninja-build
  #   - make
  #   - cmake
  #   # - python
  #   # - python-dev
  #   - python3
  #   - python3-dev
  #   - python-setuptools

- name: Install compilers
  package:
    name: "{{ compilers }}"
    state: present
  # vars:
  #   packages:
  #   - gcc
  #   - g++
  #   - gfortran

- name: Install libraries
  package:
    name: "{{ libraries }}"
    state: present
  # vars:
  #   packages:
  #   - libopenmpi-dev
  #   - libblas-dev
  #   - liblapack-dev

# - debug:
#     msg: "distribution {{ ansible_distribution }} "

- name: load openmpi module on fedora
  shell: "module load mpi/openmpi-x86_64"
  when: ansible_distribution == 'Fedora'
  become: no

# - name: list modules
#   shell: module list
#   when: ansible_distribution == 'Fedora'
#   become: no

- name: Install PETSc dependencies
  package:
    name: "{{ petsc_dependencies }}"
    state: present
    update_cache: yes
  # vars:
  #   packages:
  #   - bison
  #   - flex

- name: Install pip
  package:
    name:  "{{ pip }}"
    state: present
  # vars:
  #   packages:
  #   - python3-pip

- name: Update pip to lates version with pip
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
      packages:
      - pip


- name: Intall meson
  pip:
    name: meson
    executable: pip3

- name: set opt_paths
  copy:
    src: "{{ role_path }}/files/opt_paths.sh"
    dest: /etc/profile.d/opt_paths.sh
    # remote_src: yes
    remote_src: no
  tags:
    - not_packer

# - name: Clean app directory structure
#   file:
#     state: absent
#     path: /opt/app/{{ item }}
#   with_items:
#   - bin
#   - lib
#   - include

- name: Creates app directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/app
    - /opt/app/bin
    - /opt/app/lib
    - /opt/app/include

- name: change app deployment ownership
  file:
    dest: /opt/app
    owner: vagrant
    group: vagrant
    recurse: yes
  tags:
    - vagrant
