---

- name: Install build-related tools
  package:
    name: "{{ build_tools }}"
    state: present
    update_cache: yes

- name: Install compilers
  package:
    name: "{{ compilers }}"
    state: present

- name: Install libraries
  package:
    name: "{{ libraries }}"
    state: present

- name: Install PETSc dependencies
  package:
    name: "{{ petsc_dependencies }}"
    state: present
    update_cache: yes


- name: Install pip
  package:
    name:  "{{ pip_install }}"
    state: present

- name: Update pip to latest version with pip
  pip:
    name: pip
    executable: "{{ pip_ex }}"
    # extra_args: "-U"
  # when: ansible_os_family != 'Archlinux'

- name:  login directory for vagrant VM
  lineinfile:
    path:  ~/.bashrc
    regexp: ^cd {{ install_location}}"
    line: "cd {{ install_location }}"
  become: no
  tags:
    - vagrant

- name: Activate openmpi module at login RedHat OS family Change
  lineinfile:
    path:  ~/.bashrc
    regexp: '^module add mpi'
    line: 'module add mpi/openmpi-x86_64'
  when: ansible_os_family == 'RedHat'
  become: no

- name: set opt_paths.sh with template
  template:
    src: opt_paths.j2
    dest: /etc/profile.d/opt_paths.sh
  tags:
    - not_packer
