---

- name: Install build-related tools
  package:
    name: "{{ build_tools }}"
    state: present
    update_cache: yes


- name: Install compilers
  package:
    name: "{{ compilers }}"
    state: present

- name: Install libraries
  package:
    name: "{{ libraries }}"
    state: present


- name: Install PETSc dependencies
  package:
    name: "{{ petsc_dependencies }}"
    state: present
    update_cache: yes


- name: Install pip
  package:
    name:  "{{ pip_install }}"
    state: present

- name: Update pip to latest version with pip
  pip:
    name: "{{ packages }}"
    executable: "{{ pip_ex }}"
  vars:
      packages:
      - pip
  # when: ansible_os_family != 'Archlinux'
  become: no

- name: Intall meson
  pip:
    name: meson
    executable: "{{ pip_ex }}"

- lineinfile:
    path:  ~/.bashrc
    regexp: '^module add mpi'
    line: 'module add mpi/openmpi-x86_64'
  when: ansible_os_family == 'RedHat'
  become: no

- name: set opt_paths
  copy:
    src: "{{ role_path }}/files/opt_paths.sh"
    dest: /etc/profile.d/opt_paths.sh
    # remote_src: yes
    remote_src: no
  tags:
    - not_packer

- name: change app deployment ownership
  file:
    dest: "{{ install_location }}"
    owner: vagrant
    group: vagrant
    recurse: yes
  tags:
    - vagrant
