---

- name: Install build-related tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - git
    - pkg-config
    - valgrind
    - ninja-build
    - make
    - cmake

- name: Install compilers
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - gcc
    - g++
    - gfortran

- name: Install libraries
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - libopenmpi-dev
    - libblas-dev
    - liblapack-dev

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Update pip to lates version with pip
  pip:
    name: pip

- name: Intall meson
  pip:
    name: meson

- name: set opt_paths
  copy:
    src: "{{ role_path }}/files/opt_paths.sh"
    dest: /etc/profile.d/opt_paths.sh
    remote_src: yes
  tags:
    - not_packer

# - name: Clean app directory structure
#   file:
#     state: absent
#     path: /opt/app/{{ item }}
#   with_items:
#   - bin
#   - lib
#   - include

- name: Creates app directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/app
    - /opt/app/bin
    - /opt/app/lib
    - /opt/app/include
