# - hosts: localhost
#   become_user: waiwera
#   become_method: su
#   become: yes
#   tasks:
---

- name: Clean fson paths
  file:
    state: absent
    path: /opt/app/{{ item }}
  with_items:
  - fson
  tags:
    - clean

- name: Fetch fson from github
  git:
    repo: 'https://github.com/josephalevin/fson.git'
    dest: /opt/app/fson
    version: master

- name: replace HOME with app directory
  replace:
    dest: /opt/app/fson/makefile
    regexp: '\$\(HOME\)'
    replace: '/opt/app'

- name: Make fson
  make:
    chdir: /opt/app/fson

- name: Make install fson
  make:
    chdir: /opt/app/fson
    target: install

- name: Remove fson downloads
  file:
    state: absent
    path: /opt/app/{{ item }}
  with_items:
  - fson
