# - hosts: localhost
#   become_user: waiwera
#   become_method: su
#   become: yes
#   tasks:
---

- name: Clean fson paths
  file:
    state: absent
    path: "{{ fson_path }}"
  tags:
    - clean

- name: Fetch fson from github
  git:
    repo: 'https://github.com/josephalevin/fson.git'
    dest:  "{{ fson_path }}"
    version: master

- name: replace HOME with app directory
  replace:
    dest: "{{ fson_path + '/makefile' }}"
    regexp: '\$\(HOME\)'
    replace: '{{ install_location }}'

- name: Make fson
  make:
    chdir: "{{ fson_path }}"

- name: Make install fson
  make:
    chdir: "{{ fson_path }}"
    target: install

- name: Remove fson downloads
  file:
    state: absent
    path:  "{{ fson_path }}"
