---

- name: Run the common tasks to setup waiwera
  include: base.yml

- name: Setup PETSc
  include: petsc.yml

- name: Setup fruit
  include: fruit.yml

- name: Setup fson
  include: fson.yml

- name: Setup and test waiwera
  #vars_file: secrets.yml
  environment:
    PETSC_DIR: /opt/app/petsc
    PETSC_ARCH: arch-linux2-c-debug
    LD_LIBRARY_PATH: "/opt/app/lib"
    PYTHONPATH: "/opt/app/PyTOUGH:/opt/app/credo2:/opt/app/supermodels-test/utils"
    PATH: "{{ ansible_env.PATH }}:/opt/app/bin:/opt/app/supermodels-test/dist"
  include: supermodels.yml

- name: Cleanup
  include: cleanup.yml

- name: change deployment ownership
  file:
    dest: /opt/app/
    owner: root
    group: root
    recurse: yes
