---
- name: Setup secrets
  include_vars: secrets.yml
  tags:
    - packer

- name: create user
  user:
   name: "{{ app_user }}"
   shell: /bin/bash
   uid: 1000
   comment: waiwera app user
  tags:
    - docker

- name: create group
  group:
   name: "{{ app_group }}"
   # shell: /bin/bash
   gid: 1000
   # comment: waiwera app user
  tags:
    - docker

# - name: Get default Variables
#   include_vars: "../vars/default.yml"

- name: Get Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Set install location
  set_fact:
    install_location: "{{ app_dir }}/waiwera"

- name: Set Paths
  set_fact:
    petsc_path: "{{ install_location + '/external/PETSc'}}"
    ld_library_path: "{{ install_location + '/lib'}}"
    bin_path: "{{ install_location + '/bin'}}"
    pkgconfig_path: "{{ install_location + '/lib/pkgconfig'}}"
    dist_path: "{{ install_location }}/dist"
    util_path: "{{ install_location }}/utils"
    include_path: "{{ install_location }}/include"

- name: Run the common tasks to setup waiwera
  include: base.yml
  become: yes
  tags:
    - setup

- name: Setup and test waiwera
  environment:
    PETSC_DIR: "{{ petsc_path }}"
    PETSC_ARCH: arch-linux2-c-debug
    LD_LIBRARY_PATH: "{{ ld_library_path }}"
    PYTHONPATH: "{{ util_path }}"
    PATH: "{{ ansible_env.PATH }}:{{ bin_path }}:{{dist_path}}:{{ ansible_env.HOME }}/.local/bin"
    PKG_CONFIG_PATH: "{{ pkgconfig_path }}"
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    LC_TYPE: en_US.UTF-8
  include: waiwera.yml
  tags:
    - app

- name: Cleanup
  include: cleanup.yml
  tags:
    - docker

- name: change app deployment ownership
  file:
    dest: "{{ install_location }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  tags:
    - docker

- name: change /usr/local deployment ownership
  file:
    dest: /usr/local
    owner: root
    group: root
    recurse: yes
  tags:
    - docker
