---

- name: Clean petsc path
  file:
    state: absent
    path: "{{ petsc_path }}"
  tags:
    - clean

- name: Fetch PETSc from bitbucket
  git:
    repo: 'https://bitbucket.org/petsc/petsc.git'
    # dest: /opt/app/petsc
    dest: "{{ petsc_path }}"
    version: 81b0e57
    # v3.10.2 doesn't work

- name: Create build directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ install_location + '/build'}}"
    - "{{ install_location + '/lib/pkgconfig'}}"

- name: change PETSc ownership
  file:
    dest: "{{ petsc_path }}"
    owner: root
    group: root
    recurse: yes
  tags:
    - docker

- name: create configure command
  set_fact:
    configure_cmd: "{{ './configure --'  + petsc_options | join(' --') }}"

- name: Running ./configure for PETSc
  command: "{{ configure_cmd }}"
  args:
    chdir: "{{ petsc_path }}"

- name: Make PETSc
  make:
    target: all
    chdir: "{{ petsc_path }}"

- name:  Check PETSc
  make:
    target: check
    chdir: "{{ petsc_path }}"


- name: Copy petsc pkgconfig
  copy:
    src: "{{ petsc_path + '/arch-linux2-c-debug/lib/pkgconfig/PETSc.pc'}}"
    dest: "{{ install_location + '/lib/pkgconfig/PETSc.pc'}}"
    remote_src: yes
