# - hosts: localhost
#   become_user: waiwera
#   become_method: su
#   become: yes
#   tasks:
---

- name: Clean petsc paths
  file:
    state: absent
    path: /opt/app/{{ item }}
  with_items:
  - petsc

- name: Fetch PETSc from bitbucket
  git:
    repo: 'https://bitbucket.org/petsc/petsc.git'
    dest: /opt/app/petsc
    version: master
    # v3.10.2 doesn't work

- name: Running ./configure for PETSc
  command: >
    ./configure --download-fblaslapack --download-triangle --download-netcdf
     --download-exodusii --download-pnetcdf --download-hdf5
     --download-ptscotch  --download-chaco
     --with-zlib
  args:
    chdir: /opt/app/petsc/
       # --with-mpi-dir=/opt/app/
# --with-fc=gfortran-6

- name: Make PETSc
  make:
    chdir: /opt/app/petsc
