---

# - debug:
#     msg: "distribution {{ ansible_distribution }} family {{ ansible_os_family }}"

# - name: load openmpi module on fedora
#   shell: "module avail"
#   when: ansible_os_family == 'RedHat'
#   become: no
#
# - name: load openmpi module on fedora
#   shell: "module add mpi/openmpi-x86_64; module list"
#   when: ansible_os_family == 'RedHat'
#   become: no
#
# - name: load openmpi module on fedora
#   shell: "module list"
#   when: ansible_os_family == 'RedHat'
#   become: no

# - name: list modules
#   shell: module list
#   when: ansible_distribution == 'Fedora'
#   become: no
- name: Clean supermodels-test path
  file:
    state: absent
    path: /opt/app/waiwera
  tags:
    - clean

- name: Fetch supermodels-test from github
  git:
    repo: "https://{{ waiwera_user | urlencode }}:{{ waiwera_pwd  | urlencode }}@github.com/johnburnell/supermodels-test.git"
    dest: /opt/app/waiwera
    version: meson

- name: Setup PETSc
  include: petsc.yml

# - name: replace HOME with app directory
#   replace:
#     dest: /opt/app/supermodels-test/makefile
#     regexp: '\$\(HOME\)'
#     replace: '/opt/app'
# - name: Run config.py
#   shell: python config.py --prefix /opt/app/waiwera  --petsc_revision=81b0e57
#   args:
#     chdir: /opt/app/waiwera


- name: Meson build
  shell: meson build --buildtype release --prefix /opt/app/waiwera # -Dlibdir=/opt/app/lib
  args:
    chdir: /opt/app/waiwera

- name: Ninja build
  shell: ninja -C build
  when: ansible_distribution != 'CentOS'
  args:
    chdir: /opt/app/waiwera/

- name:  Ninja build - CentOS
  shell: "ninja-build -C build"
  when: ansible_distribution == 'CentOS'
  args:
    chdir: /opt/app/waiwera/

- name: Set file permissions supermodels
  file:
    dest: /opt/app/waiwera
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=rwX
    recurse: yes
  tags:
    - docker
