---

- name: waiwera - Fetch waiwera from repository
  git:
    repo: "https://{{ waiwera_repo }}"
    dest:  "{{ waiwera_path }}"
    version: "{{ waiwera_version }}"
    update: yes
    force: yes
  register: waiwera_git
  tags:
    - fetch

- name: Build
  block:

  - name: waiwera - Meson build
    shell: meson build --buildtype={{ petsc_arch }} --prefix={{ base_dir }} -Dlibdir=lib -Dset_rpath=true
    args:
      chdir: "{{ waiwera_path }}"
      executable: /bin/bash
    tags:
      - meson
      - build

  - name: waiwera - ninja
    block:
    - name: waiwera - Ninja build
      shell: ninja -C build
      when: ansible_distribution != 'CentOS'
      args:
        chdir: "{{ waiwera_path }}"

    - name: waiwera - Ninja build, CentOS
      shell: "ninja-build -C build"
      when: ansible_distribution == 'CentOS'
      args:
        chdir: "{{ waiwera_path }}"
    tags:
      - ninja
      - build

  when: ((waiwera_git.changed == true) or ( waiwera_update == 'true'))
