---

- name: check for user install of meson
  set_fact:
  extra_args: "--user"
  when: ansible_user_id != root
  tags:
    - local

- name: check for user install of meson
  set_fact:
  extra_args: ""
  when: ansible_user_id == root
  tags:
    - docker
    - root

- name: pip3 install
  pip:
    name: "{{ meson_version }}"
    executable: "{{ pip_ex }}"
    extra_args: "{{ extra_args }}"
