---

- name: meson - pip install local --user using pip3
  pip:
    name: "{{ meson_version }}"
    executable: "{{ pip_ex }}"
    extra_args: "--user"
  tags:
    - local
  when: docker_run is not defined

- name: meson - install for root using pip3
  pip:
    name: "{{ meson_version }}"
    executable: "{{ pip_ex }}"
    # extra_args: "--user"
  tags:
      - docker
      - root
  when: docker_run is defined
