# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: debian:9

options:
  size: 1x

pipelines:
  default:
    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export IMAGE_NAME=thar102/waiwera:$BITBUCKET_BRANCH
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME . --build-arg "git_user=$W_USER" --build-arg "git_pwd=$W_PWD"  --build-arg "base_dir=/opt"
          - docker container run --rm $IMAGE_NAME python unit_tests.py
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
definitions:
    services:
        docker: # we specifically disallow modifying image.
            memory: 3072 #Megabytes
