
- include_role:
    name: packages
  vars:
    app_group: "{{ v_group }}"
    app_user: "{{ v_user }}"
    base_dir: "{{ v_dir }}"

- name: Include common role
  import_role:
    name: common
  vars:
    app_group: "{{ v_group }}"
    app_user: "{{ v_user }}"
    base_dir: "{{ v_dir }}"
  become: no

- name: Change login directory for vagrant VM
  lineinfile:
    path:  ~/.bashrc
    regexp: ^cd {{ waiwera_path}}"
    line: "cd {{ waiwera_path }}"
  tags:
    - never
    - vagrant

- name: Waiwera install
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ bin_path }}:{{ local_bin }}:{{ petsc_bin }}"
  block:
  - name: waiwera - Ninja build install
    shell: ninja -C build install
    when: ansible_distribution != 'CentOS'
    args:
      chdir: "{{ waiwera_path }}"

  - name: waiwera - Ninja build install, CentOS
    shell: "ninja-build -C build install"
    when: ansible_distribution == 'CentOS'
    args:
      chdir: "{{ waiwera_path }}"
  tags:
    - ninja
    - build
  become: no