---

- name: Build Waiwera with and install dependencies
  hosts: localhost
  tasks:
  - name: get the username running the deploy
    become: false
    local_action: command whoami
    register: user

  - set_fact:
    install_dir: "/home/{{ user }}/waiwera"

  - include_role:
      name: packages
    vars:
      app_group: "{{ user }}"
      app_user: "{{ user }}"
      base_dir: "{{ install_dir }}"
    become: yes

  - name: Import common role
    import_role:
      name: common
    vars:
      app_group: "{{ user }}"
      app_user: "{{ user }}"
      base_dir: "{{ install_dir }}"
    become: no

  - name: Waiwera install
    block:
    - name: waiwera - Ninja build install
      shell: ninja -C build install
      when: ansible_distribution != 'CentOS'
      args:
        chdir: "{{ waiwera_path }}"

    - name: waiwera - Ninja build install, CentOS
      shell: "ninja-build -C build install"
      when: ansible_distribution == 'CentOS'
      args:
        chdir: "{{ waiwera_path }}"
    tags:
      - ninja
      - build
    become: no
