---
- name: Build Image
  hosts: all
  tasks:

  - import_role:
      name: get_variables
    become: yes
    become_user: '{{ app_user }}'

  - import_role:
      name: common
    become: yes
    become_user: '{{ app_user }}'
