---

- name: zofu - Set path variable
  set_fact:
    zofu_path: "{{ software_path }}/zofu"
    zofu_build_path: "{{ zofu_path + '/build' }}"

- name: zofu - tidy path
  file:
    state: absent
    path: "{{ zofu_path }}"
  tags:
    - never
    - tidy

- name: zofu - fetch from github
  git:
    repo: 'https://github.com/acroucher/zofu.git'
    dest: "{{ zofu_path }}"
    version: master
  tags:
    - fetch

- name: zofu - change ownership
  file:
    dest: "{{ zofu_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes
  when: docker_run == true

- name: zofu - meson build
  shell: 'meson build --buildtype=release --prefix={{ base_dir }} --libdir={{ lib_path }} --includedir={{ include_path }}'
  args:
    chdir: "{{ zofu_path }}"
  tags:
    - meson
    - build

- name: zofu - ninja steps
  block:
    - name: zofu - ninja build
      shell: ninja
      args:
        chdir: "{{ zofu_build_path }}"

    - name: zofu - ninja test
      shell: ninja test
      args:
        chdir: "{{ zofu_build_path }}"

    - name: zofu - ninja install
      shell: ninja install
      args:
        chdir: "{{ zofu_build_path }}"
  tags:
    - ninja
    - build