- hosts: localhost
  become: yes
  become_user: root
  become_method: su
  tasks:
  - name: Install multiple base packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - g++-6
      - bison
      - flex
      - cmake
      - git
      - valgrind
      - zlib1g-dev
      - python
      - gem
      - rake
      - gfortran-6
      - openmpi-bin
      - libopenmpi-dev

  - name: Symlink gfortran-6 to gfortran
    file:
      src: /usr/bin/gfortran-6
      dest: /usr/bin/gfortran
      state: link

  - name: Install python pip
    apt:
      name: python-pip
      state: present

  - name: Update pip to lates version with pip
    pip:
      name: pip

  - name: Intall pip packages
    pip:
      name:
        - virtualenv
        - h5py
        - virtualenvwrapper
        - numpy
        - shapely
        - future
        - pillow
        - matplotlib
        - docutils
        - scipy
        - meshio

  - name: set opt_paths
    copy:
      src: /srv/ansible/files/opt_paths.sh
      dest: /etc/profile.d/opt_paths.sh
      remote_src: yes

  - name: Clean app directory structure
    file:
      state: absent
      path: /opt/app/{{ item }}
    with_items:
    - bin
    - lib
    - include

  - name: Creates app directory structure
    file:
      path: "{{ item }}"
      state: directory
      owner: waiwera
      group: waiwera
    with_items:
      - /opt/app
      - /opt/app/bin
      - /opt/app/lib
      - /opt/app/include
