- hosts: localhost
  become_user: root
  become_method: sudo
  tasks:
  - name: Clean fruitpy and fruit paths
    file:
      state: absent
      path: /opt/app/{{ item }}
    with_items:
    - fruitpy
    - fruit

  - name: Fetch fruitpy from github
    git:
      repo: 'https://github.com/acroucher/FRUITPy.git'
      dest: /opt/app/fruitpy
      version: v.0.3.2

  - name: pip install fruitpy
    pip:
      name: file:///opt/app/fruitpy

  - name: Dowload and unarchive fruit
    unarchive:
      src: https://sourceforge.net/projects/fortranxunit/files/fruit_3.4.3/fruit_3.4.3.zip/download
      dest: /opt/app/
      remote_src: yes

  - name: Move fruit no non-versioned directory name, if it doesn't exist
    command: mv -n /opt/app/fruit_3.4.3 /opt/app/fruit

  - name: copy fruit makefile from fruitpy
    copy:
      src: /opt/app/fruitpy/fruit_makefile
      dest: /opt/app/fruit/makefile

  - name: replace HOME with app directory
    replace:
      dest: /opt/app/fruit/makefile
      regexp: '\$\(HOME\)'
      replace: '/opt/app'

  - name: Make fruit
    make:
      chdir: /opt/app/fruit

  - name: Make install fruit
    make:
      chdir: /opt/app/fruit
      target: install

  - name: Copy .mod files from fruit to the include directory
    copy:
      src: '/opt/app/fruit/{{ item }}.mod'
      dest: '/opt/app/include/{{ item }}.mod'
      remote_src: yes
    with_items:
      - fruit
      - fruit_util
      - fruit_mpi

  - name: Rake install fruit
    command: rake install
    args:
      chdir: /opt/app/fruit/fruit_processor_gem
    become: yes
