- hosts: all
  tasks:
  - name: Fetch fson from github
    git:
      repo: 'https://github.com/josephalevin/fson.git'
      dest: /opt/app/fson
      version: master

  - name: replace HOME with app directory
    replace:
      dest: /opt/app/fson/makefile
      regexp: '\$\(HOME\)'
      replace: '/opt/app'

  - name: Make fson
    make:
      chdir: /opt/app/fson

  - name: Make install fson
    make:
      chdir: /opt/app/fson
      target: install
