---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Install multiple base packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - g++-6
      - bison=2:3.0.4*
      - flex=2.6.1*
      - cmake=3.7.2*
      - git
      - valgrind=1:3.12.0*
      - zlib1g-dev=1:1.2.8*
      - python
      - gem
      - rake
      - gfortran-6=6.3.0*
      # - openmpi-bin
      # - libopenmpi-dev

  - name: Symlink gfortran-6 to gfortran
    file:
      src: /usr/bin/gfortran-6
      dest: /usr/bin/gfortran
      state: link

  - name: Install python pip
    apt:
      name: python-pip
      state: present

  - name: Update pip to lates version with pip
    pip:
      name: pip

  - name: Intall pip packages
    pip:
      name:
        - virtualenv
        - h5py
        - virtualenvwrapper
        - numpy
        - shapely
        - future
        - pillow
        - matplotlib
        - docutils
        - scipy
        - meshio

  - name: set opt_paths
    copy:
      src: /vagrant/ansible/files/opt_paths.sh
      dest: /etc/profile.d/opt_paths.sh
      remote_src: yes

  # - name: add to environment
  #   lineinfile:
  #     path: /etc/profiile.d/petsc_paths.sh
  #     state: present
  #     line: "exyort {{ item }}"
  #   with_items:
  #     - PETSC_DIR=/opt/app/petsc
  #     - PETSC_ARCH=arch-linux2-c-debug
  #     - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/app/lib
  #     - PYTHONPATH=/opt/PyTOUGH:/opt/app/credo2:/opt/app/supermodels-test/utils
  #     - PATH=$PATH:/opt/app/bin:/opt/app/supermodels-test/dist

  - name: Creates directory
    file:
      path: "{{ item }}"
      state: directory
      owner: vagrant
      group: vagrant
    with_items:
      - /opt/app
      - /opt/app/bin
      - /opt/app/lib
      - /opt/app/include

- hosts: all
  become_user: root
  become_method: sudo
  tasks:
  - name: Dowload and unarchive openmpi
    unarchive:
      src: https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.3.tar.gz
      dest: /opt/app/
      remote_src: yes

  - name: Move openmpi no non-versioned directory name
    command: mv /opt/app/openmpi-3.1.3 /opt/app/openmpi

  - name: Running ./configure for openmpi
    command: >
      ./configure --prefix="/opt/app/"  FC=gfortran-6
    args:
      chdir: /opt/app/openmpi

  - name: Make openmpi
    make:
      chdir: /opt/app/openmpi

  - name: Make install openmpi
    make:
      chdir: /opt/app/openmpi
      target: install
    become: yes

  - name: Fetch PETSc from bitbucket
    git:
      repo: 'https://bitbucket.org/petsc/petsc.git'
      dest: /opt/app/petsc
      version: v3.10.1

  - name: Running ./configure for PETSc
    command: >
      ./configure --download-fblaslapack --download-triangle --download-netcdf
       --download-exodusii --download-pnetcdf --download-hdf5
       --download-ptscotch  --download-chaco
       --with-mpi-dir=/opt/app/openmpi
       --with-zlib
       # --with-fc=gfortran-6
    args:
      chdir: /opt/app/petsc/

  - name: Make PETSc
    make:
      chdir: /opt/app/petsc

- import_playbook: fruit.yml
- import_playbook: fson.yml
# - hosts: all
#   remote_user: vagrant
#   tasks:
#     - name: execute unit
#       script: /home/vagrant/supermodels-test/unit_tests.py
