---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Install multiple base packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - gfortran-6=6.3.0*
      - libopenmpi-dev=2.0.2*
      - bison=2:3.0.4*
      - flex=2.6.1*
      - cmake=3.7.2*
      - git
      - valgrind=1:3.12.0*
      - cvs
      - zlib1g-dev=1:1.2.8*
      - python
      - g++=4:6.3.0*
      - gem
      - rake

  - name: Install python pip
    apt:
      name: python-pip
      state: present

  - name: Update pip to lates version with pip
    pip:
      name: pip

  - name: Intall pip packages
    pip:
      name:
        - virtualenv
        - h5py
        - virtualenvwrapper
        - numpy
        - shapely
        - future
        - pillow
        - matplotlib
        - docutils
        - scipy
        - meshio

  - name: set opt_paths
    copy:
      src: /vagrant/ansible/files/opt_paths.sh
      dest: /etc/profile.d/opt_paths.sh
      remote_src: yes

  # - name: add to environment
  #   lineinfile:
  #     path: /etc/profiile.d/petsc_paths.sh
  #     state: present
  #     line: "exyort {{ item }}"
  #   with_items:
  #     - PETSC_DIR=/opt/app/petsc
  #     - PETSC_ARCH=arch-linux2-c-debug
  #     - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/app/lib
  #     - PYTHONPATH=/opt/PyTOUGH:/opt/app/credo2:/opt/app/supermodels-test/utils
  #     - PATH=$PATH:/opt/app/bin:/opt/app/supermodels-test/dist

  - name: Creates directory
    file:
      path: {{ item }}
      state: directory
      owner: vagrant
      group: vagrant
    with_items:
      - /opt/app
      - /opt/app/bin
      - /opt/app/lib
      - /opt/app/include

- hosts: all
  tasks:
  - name: Fetch PETSc from bitbucket
    git:
      repo: 'https://bitbucket.org/petsc/petsc.git'
      dest: /opt/app/petsc
      version: v3.10.1

  - name: Running ./configure for PETSc
    command: >
      ./configure --download-fblaslapack --download-triangle --download-netcdf
       --download-exodusii --download-pnetcdf --download-hdf5
       --download-ptscotch  --download-chaco --download-openmpi
       --with-zlib --with-fc=gfortran-6
    args:
      chdir: /opt/app/petsc/

  - name: Make PETSc
    make:
      chdir: /opt/app/petsc
    become: yes


- hosts: all
  tasks:
  - name: pip install fruitpy
    pip:
      name: git+git@github.com:acroucher/FRUITPy.git@v0.3.2

  

# https://sourceforge.net/projects/fortranxunit/files/fruit_3.4.3/fruit_3.4.3.zip/download
# - name: Unarchive a file that needs to be downloaded (added in 2.0)
#   unarchive:
#     src: https://example.com/example.zip
#     dest: /usr/local/bin
#     remote_src: yes
# git clone https://github.com/acroucher/FRUITPy.git /home/vagrant/fruitpy

# - hosts: all
#   remote_user: vagrant
#   tasks:
#     - name: execute unit
#       script: /home/vagrant/supermodels-test/unit_tests.py
