- hosts: all
  tasks:
  - name: Clean supermodels-test path
    file:
      state: absent
      path: /opt/app/supermodels-test

  - name: Fetch supermodels-test from github
    git:
      repo: 'https://jposunz:wapiti21@github.com/johnburnell/supermodels-test.git'
      dest: /opt/app/supermodels-test
      version: testing

  - name: replace HOME with app directory
    replace:
      dest: /opt/app/supermodels-test/makefile
      regexp: '\$\(HOME\)'
      replace: '/opt/app'

  - name: Make the supermodels-test
    make:
      chdir: /opt/app/supermodels-test

  - name: Execute supermodels unit_tests
    command: python unit_tests.py
    args:
      chdir: /opt/app/supermodels-test
