---

- name: Get Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  tags:
    - always

- name: Set waiwera path variables
  set_fact:
    waiwera_path: "{{ base_dir }}/waiwera"
    bin_path: "{{ base_dir }}/bin"
    lib_path: "{{ base_dir }}/lib"
    include_path: "{{ base_dir }}/include"
    software_path: "{{ base_dir }}/software"
    local_bin: "/home/{{ app_user }}/.local/bin"

- name: Set petsc layer path variables
  set_fact:
    petsc_path: "{{ software_path }}/PETSc"

- name: Set petsc petsc_arch path
  set_fact:
    petsc_arch_path: "{{ petsc_path }}/{{ petsc_arch }}"

- name: Set petsc bin bath
  set_fact:
    petsc_lib: "{{ petsc_arch_path }}/lib"
    petsc_bin: "{{ petsc_arch_path }}/bin"

- name: Set pkgconfig layer path variables
  set_fact:
     pkgconfig_path: "{{ lib_path }}/pkgconfig"